### ISSUE TITLE
Don't compile on XE3: FinalizeRecord not found

### ISSUE THREAD

**Issue by Mik-** [MahdiSafsafi/DebugEngine#1]
I could not compile with XE3 because of the two occurences of FinalizeRecord in DebugEngine.DebugInfo (Line 1672) and DebugEngine.Disasm (Line 606).

I fixed it with
`PExportInfo(FExportList[I])^ := Default(TExportInfo); // DebugEngine.DebugInfo Line 1672`
and
`DisasmInfo := Default(TDisasmInfo); // DebugEngine.Disasm Line 606`

As I don't know, in which Version of Delphi FinalizeRecord arrived and how you would resolve it (ifdef or something else) I commit no pull request.

**Comment by MahdiSafsafi** [comment]
Hi Mik,
```FinalizeRecord``` function is declared in System unit (System.pas). Basically XE3 supports that function !
So my question is do you use any 3rd party libraries beyond DebugEngine ?

**Comment by MahdiSafsafi** [comment]
Also, note that your fix is not correct. The purpose of ```FinalizeRecord``` function is to deallocate record memory. Thus your fix will not prevent memory leaks.

**Comment by Mik-** [comment]
Hi Mahdi,
my System.pas just contains the function _FinalizeRecord. No Version without underscore.

I think my fix works well. If I comment the FinalizeRecord calls out, I got a memory leaks message on shutdown. It doesn't appear with my solution. If I assign a new, empty record (with no strings allocated), the old record should be freed correctly.

I use a lot of 3rd party libraries. Do you have a special in mind? And why should it remove the visibility of a FinalizeRecord. The compiler complains about _Undeclared Identifier: FinalizeRecord_.

BTW: Great work at all (and I'd like to see line numbers in stack trace :-)

**Comment by MahdiSafsafi** [comment]
Hi Mik,
Maybe the error is related to 3rd party libraries. It may happen that some library have a function called ```FinalizeRecord``` So the compiler will get confused what to select !
Try to change ```FinalizeRecord(xx,xx)``` to : ```System.FinalizeRecord(xx,xx)``` and let me know please !
About line numbers, yep I will support it soon :)

**Comment by Mik-** [comment]
I did a fresh clone of your project. I disabled all 3rd party packages. Same error as before: _Undeclared Identifier: 'FinalizeRecord'_
I tried System.FinalizeRecord and System._FinalizeRecord . No change. It's weird, cause _FinalizeRecord is declared in my System.pas

**Comment by MahdiSafsafi** [comment]
Hello Mik,
Good news, I fixed the error, please use the last commit.

Mahdi.

**Comment by Mik-** [comment]
Works like a charm! Thank you very much.

Mik
