### ISSUE TITLE
missing DebugEngine.ThreadUtils

### ISSUE THREAD

**Issue by mariuszmaximus** [MahdiSafsafi/DebugEngine#3]
In DebugEngineDemo.dpr in uses is file "DebugEngine.ThreadUtils" but not exists in repository

**Comment by MahdiSafsafi** [comment]
Hi mariuszmaximus,
DebugEngine.ThreadUtils is an internal unit (not published yet). I used the repo's project when I was developing it. For the moment, you can strip it out of DebugEngineDemo.dpr until I release un update.

Mahdi.

**Comment by limelect** [comment]
I used https://github.com/deadserious/threadutils

**Comment by mariuszmaximus** [comment]
Thank you very much!
