### ISSUE TITLE
    if not IsBadCodePtr(Pointer(Arg.Imm.Value)) then

### ISSUE THREAD

**Issue by limelect** [MahdiSafsafi/DebugEngine#4]
Using Delphi berlin free.
    if not IsBadCodePtr(Pointer(Arg.Imm.Value)) then
On DebugEngine.Disasm;
Getting access violation.!!!!!
Cannot debug since i do not have the source.
With out the Delphi IDE the exe run OK.

**Comment by MahdiSafsafi** [comment]
Hi limelect,
Can you provide more details please ?

Mahdi.

**Comment by limelect** [comment]
As i said The EXE is ok.
But wile on the IDE berlin i get on this instruction
if not IsBadCodePtr(Pointer(Arg.Imm.Value)) then
an access violation.
Since my Berlin is free i cannot debug - No sources.
So i cannot help more then this.
It is the Test project.

**Comment by limelect** [comment]
It seem to be Ok now .
