### ISSUE TITLE
Bug in ConvertMapToSMap

### ISSUE THREAD

**Issue by JensBorrisholt** [MahdiSafsafi/DebugEngine#6]
Hello

I belive there is a bug in ConvertMapToSMap, atleast it raises an exception parsing a certain map file, and that leads to an endless loop. 

I've attatched a small demo application reproducing the exception. 

I've made a small modification to  the DebugEngine.DebugInfo unit. I've introduced a global variable called DebugCount. It's jous used for counting iterations. 

But in short. Set a breakpoint in line 1083 in my version of DebugEngine.DebugInfo. Run the application and press the button. 

The code can be found here: http://borrisholt.dk/GitHub/ExceptionTest.7z

Jens Borrisholt

**Comment by MahdiSafsafi** [comment]
Hello again !
This is more like a **FEATURE** to implement AND **NOT A BUG** !
```ConvertMapToSMap``` doesn't support converting a map that DOES NOT HAVE **LINE NUMBERS INFORMATION** !
Once, your map ('ExceptionTest.map') contains **Line number information**, ```ConvertMapToSMap``` will work correctly.

Mahdi.

**Comment by JensBorrisholt** [comment]
*** SORRY *** I linked to the wrong project

Please download 
http://borrisholt.dk/GitHub/PARSER_ERROR_DEMO.7z

And then look at my original message.

**Comment by MahdiSafsafi** [comment]
Yeah, you're right !

The problem is that the map 'TradeEx.map' contains a lot of units. DebugEngine limits units to 1000 unit. But 'TradeEx.map' uses more than 1000 unit. And that's why you got AV error.

Fixing this issue is easy, just give a few minutes and I'll release a patch to solve this issue.

Mahdi.

**Comment by JensBorrisholt** [comment]
Thanks a lot. You should consider making it a list instad of an array. Then you are not limited. :)

**Comment by MahdiSafsafi** [comment]
I can't use List ! ```ConvertMapToSMap``` is faster because I implemented it using the low level way ! If I use List, ```ConvertMapToSMap``` will take likely more than one **minute** to convert the map file ! (using low-level it just takes [1 .. 4] **second max** !). Besides 'SMAP' is a binary format.

**Comment by MahdiSafsafi** [comment]
Please confirm if the latest commit fixed your issue.

**Comment by JensBorrisholt** [comment]
Hello

"Please confirm if the latest commit fixed your issue." the answer to that is yes and no :) 

It fixes the parsing issue that I reported. But when I put your code into my real project I ran into some new problems. 

still in unit DebugEngine.DebugInfo

function RegisterSegment(PSegment: PSMapSegment): PRuntimeSegment;

An AV can occour if PSegment^.SegStartAddress is zero. Then PSegment^.SegStartAddress - LModuleImageBase becomes a negative value and since PSegment^.SegStartAddress is a cardinal and LModuleImageBase is a NativeUInt then it doesn't work. The work arround is to convert it all into integers:

Line 1707 :
    Result^.SegStartAddress := Pointer((PSegment^.SegStartAddress - LModuleImageBase) + FModule.ModuleHandle);

Changed to :
    Result^.SegStartAddress := Pointer((Integer(PSegment^.SegStartAddress) - Integer(LModuleImageBase)) + Integer(FModule.ModuleHandle));

And that leads to an other AV for the same reasons:

function LineSortCompare(Item1, Item2: Pointer): Integer;

if PLineNumberSource(Item1)^.Line^.Offset is zero then you try to put an negative value into a NativeUInt and that doesn't work

So line 1690 consecutive :

function LineSortCompare(Item1, Item2: Pointer): Integer;
begin
  Result := NativeUInt(PLineNumberSource(Item1)^.Source^.SegId) - NativeUInt(PLineNumberSource(Item2)^.Source^.SegId);
  if Result = 0 then
    Result := NativeUInt(PLineNumberSource(Item1)^.Line^.Offset) - NativeUInt(PLineNumberSource(Item2)^.Line^.Offset);
end;

Changed to 

function LineSortCompare(Item1, Item2: Pointer): Integer;
begin
  Result := NativeInt(PLineNumberSource(Item1)^.Source^.SegId) - NativeInt(PLineNumberSource(Item2)^.Source^.SegId);
  if Result = 0 then
    Result := NativeInt(PLineNumberSource(Item1)^.Line^.Offset) - NativeInt(PLineNumberSource(Item2)^.Line^.Offset);
end;

And then it all works. 

I can not reproduce it in my test project, but I can reproduce it in my real world project.

**Comment by MahdiSafsafi** [comment]
I never saw ```SegStartAddress = 0``` !  ```SegStartAddress``` is a RELATIVE OFFSET to the module's ImageBase .
Also, this conversion ```Result^.SegStartAddress := Pointer((Integer(PSegment^.SegStartAddress) - Integer(LModuleImageBase)) + Integer(FModule.ModuleHandle));``` is a potentially scary ! ```ModuleHandle && NativeUInt``` are a ```NativeUInt type```. Converting them to Integer may lead to undefined behavior.

So, please open a new issue and provide me necessary steps (better a Demo) to reproduce the issue. So I can work on that issue and possibly write a fix.

If you're not able to reproduce the issue, please try edit **DebugEngine.DebugInfo** with this function:
```
  function RegisterSegment(PSegment: PSMapSegment): PRuntimeSegment;
  begin
    { Convert segment to run time segment and register it. }
    GetMem(Result, SizeOf(TRuntimeSegment));
    Result^.SegId := PSegment^.SegId;
    Result^.SegLength := PSegment^.SegLength;
    { Module could be loaded at a different address space
      specified by Delphi. So we need to fix segment start address. }
    if (PSegment^.SegStartAddress = 0) then
      Result^.SegStartAddress :=Pointer( FModule.ModuleHandle)
    else
      Result^.SegStartAddress := Pointer((PSegment^.SegStartAddress - LModuleImageBase) + FModule.ModuleHandle);

    Result^.SegEndAddress := Pointer(PByte(Result^.SegStartAddress) + Result^.SegLength);

    if not FModule.IsAddressInModuleRange(Result^.SegStartAddress) then
    begin
      FreeMem(Result);
      Result := nil;
    end
    else
      FRTSegments.Add(Result);
  end;
```
And let me know if this fixed your problem.

**Comment by JensBorrisholt** [comment]
Yes it solved the issue. Atleast when you have modified the sort procedure aswell.

if PLineNumberSource(Item1)^.Line^.Offset id 0 then you'll get an AV using NativeUint. I've changed it to Int64


function LineSortCompare(Item1, Item2: Pointer): Integer;
begin
  Result := Int64(PLineNumberSource(Item1)^.Source^.SegId) - Int64(PLineNumberSource(Item2)^.Source^.SegId);
  if Result = 0 then
    Result := Int64(PLineNumberSource(Item1)^.Line^.Offset) - Int64(PLineNumberSource(Item2)^.Line^.Offset);
end;

**Comment by JensBorrisholt** [comment]
Please update the source and I'll pull againg at have a new go with the original source

**Comment by MahdiSafsafi** [comment]
Does this :
```
function LineSortCompare(Item1, Item2: Pointer): Integer;
begin
  Result := PLineNumberSource(Item1)^.Source^.SegId - PLineNumberSource(Item2)^.Source^.SegId;
  if Result = 0 then
    Result := PLineNumberSource(Item1)^.Line^.Offset - PLineNumberSource(Item2)^.Line^.Offset;
end;
```
Works for you ?

**Comment by JensBorrisholt** [comment]
Is it possible to excluge stacktrace generating for exception with in try .. except blocks?
