### ISSUE TITLE
Possible AV in DebugEngine.Trace => GetStackOffset

### ISSUE THREAD

**Issue by JensBorrisholt** [MahdiSafsafi/DebugEngine#8]
Line 1974: J := NativeUInt(PFrame^.CallerFrame) - NativeUInt(PFrame);

if NativeUInt(PFrame^.CallerFrame) > NativeUInt(PFrame) then you get an AV since you are casting to NativeUInt.

**Comment by MahdiSafsafi** [comment]
I don't think so ! I'm casting Pointer to NativeUInt. AFAIK Pointers must be casted to NativeUInt type.

**Comment by JensBorrisholt** [comment]
It's ok. I have gone back to the JCL frame work. There are to manny exceptions in this framework. Eventhougt I like the idea very much, there is still a lot of work to be done. If you use it in a large scale project it crashes!

**Comment by MahdiSafsafi** [comment]
Sorry for that !
